### ISSUE TITLE
Als loco, kann ich auf den Namen eines anderen locos in der Job-Übersicht klicken, um ihr oder ihm eine Nachricht zu schicken.

### ISSUE THREAD

**Issue by rbf** [ortoloco/ortoloco#28]
Damit die E-Mail-Adressen nicht öffentlich werden, könnten wir einen "reduzierten" Version der "Mail Page" verwenden.

**Comment by motu55** [comment]
I made an implementation proposal (I was not aware, that somebody else was already assigned, sorry about that you can also revert my commit)
about my implementation:
every loco has a new flag which describes if he can be contacted by others locos or not, default is false so that people can protect theri email if they want to.
the rest is straight forward. contact form etc

**Comment by rbf** [comment]
Thanks for the implementation! :+1: 

I just tried to change the flag on my own profile and the change wasn't saved.

Anyway, the message says that the email address will not be visible. If so, there is no need to have the option in the profile IMO.

Are the messages sent from the `info@ortoloco.ch` Address?

**Comment by motu55** [comment]
i made a mistake sorry for that the profile should now work. maybe we need another push to live. 

About the other issues/questions

- the flag in the profile is meant to see if locos even want to receive email from other locos 
- there is a new contact form which shows only the name of the loco you want to contact
- discussable is the idea to mark the locos which can be accessed by contact form

i think since people will not be aware of this feature until it is meantioned to the locos by email. I think we can discuss that at the next itloco meeting if you will be there

**Comment by motu55** [comment]
@rbf @olmaga since we have an pretty nasty bug in production I think we need to push the last commit i di for this ticket to live

**Comment by rbf** [comment]
What is the _pretty nasty bug_?

**Comment by motu55** [comment]
@rbf  users cannot update their profiles see comment and commit above

**Comment by rbf** [comment]
Ok, I just tested it. I thought it was only related to the newly added checkbox.

If the user recipient of the email will not see the author's email but the ortoloco email instead (so no private information is leaked without consent), IMO we can remove the checkbox and the new flag altogether. I don't think users visit and update their profiles very often. And for that reason I think that this in not an very very bad bug either. But you are right, the fix needs to be released.

What do you think?

**Comment by bdittes** [comment]
My five cents on the discussion: Since the checkbox is already implemented, why not keep it but default to true? I agree that no imformation is leaked, so turning it on by default is fine, but some people may still want to turn it off. (The mail sent from the form could contain a hint 'Wenn du diese Nachrichten nicht mehr erhalten möchtest...')

**Comment by rbf** [comment]
@bdittes Makes sense. :+1:

**Comment by tinaortoloco** [comment]
Scheint zu funktionieren. :-)
Wohin geht aber eine allfällige Antwort der Person, die übers my.ortoloco-Kontaktformular angeschrieben wurde? Absender ist ja Mr. Super-Duper...

**Comment by motu55** [comment]
der absender ist der eingeloggte user, respektive ie emailadresse davon.
die logik ist wie folgt:
normaler loco: sieht nur ein umschlag symbol wenn die person dies laut ihrem persönlichem profil zulässt.
bereichsleiter: sieht den knop für eine email an alle sowie ein umschlag symbol für jeden user bei jobs welche seinem tätigkeitsbereich entschrechen
admin: sieht bei ellen usern bei allen jobs ein umschlag symbol sowie den knopf um allen eingschriebenen eine email zu schreiben
